config/routes.rb
Rails.application.routes.draw do
  get '/' => 'cooks#index'
  get 'cooks/likes' => 'cooks#likes'

  resources :cooks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cook.rb
class Cook < ApplicationRecord
    validates :image, {presence: true}
    validates :name, {presence: true}
    validates :material, {presence: true}
    validates :Process, {presence: true}
    validates :memo, {presence: true}
    validates :score, {presence: true}

    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :count

    def count
        @count = Cook.all.count
    end
end

app/controllers/cooks_controller.rb
class CooksController < ApplicationController
  def index
    @cooks = Cook.all.order(created_at: :desc)
  end

  def new
    @cook = Cook.new
  end

  def create
    @cook = Cook.new(cook_params)
    if @cook.save
      flash[:notice] = "また一つ覚えたぞー！！！"
      redirect_to("/")
    else
      render("new")
    end
  end

  def show
    @cook = Cook.find(params[:id])
  end

  def edit
    @cook = Cook.find(params[:id])
  end

  def update
    @cook = Cook.find(params[:id])
    if @cook.update(cook_params)
      flash[:notice] = "さらに美味しくなりました！"
      redirect_to(@cook)
    else
      render("edit")
    end
  end

  def destroy
    @cook = Cook.find(params[:id])
    @cook.destroy
    flash[:notice] = "レシピを削除しました"
    redirect_to(cooks_path)
  end

  def cook_params
    params.require(:cook).permit(:name, :material, :Process, :memo, :score, :image)
  end

  def likes
    @cooks = Cook.where("score >= ?", 90)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cooks_helper.rb
module CooksHelper
end

app/views/cooks/edit.html.erb
<div class="new-cook">
    <div class="container">
        <div class="new-cook-wrapper">
            <div class="new-cook-line">
                <%= image_tag @cook.image.url, class:"edit-img"%>
            </div>
            <%= form_with(model: @cook) do |f|%>
            <%= render("shared/error_message", model: f.object)%>
                <div class="new-cook-line">
                    <p><%= f.label :name, "-料理名-" %></p>
                    <p><%= f.text_field :name, class:"text-field",
                        placeholder: "例: 肉じゃが" %></p>
                </div>
                <div class="new-cook-line">
                    <p><%= f.label :material, "-材料-" %></p>
                    <p><%= f.text_area :material, class:"text-field area" %></p>
                </div>
                <div class="new-cook-line">
                    <p><%= f.label :Process, "-工程-" %></p>
                    <p><%= f.text_area :Process, class:"text-field area" %></p>
                </div>
                <div class="new-cook-line">
                    <p><%= f.label :memo, "-メモ-" %></p>
                    <p><%= f.text_area :memo, class:"text-field area" %></p>
                </div>
                <div class="new-cook-line submit-line">
                <p><%= f.submit "さらに美味しく！", {class: "submit"} %></p>
                </div>
            <% end %>

        </div>
    </div>
</div>

app/views/cooks/index.html.erb
<div class="index">
    <div class="container">
        <div class="index-wrapper">
          <% @cooks.each do |cook|%>
            <div class="index-content">
              <%= link_to(cook) do %>
                <div class="index-content-image">
                    <%= image_tag cook.image.url, class:"index-img"%>
                </div>
                <div class="index-content-name">
                    <h2>
                    <%= cook.name %>
                    <% if cook.score >= 90 %>
                      <span class="fa fa-heart"></span>
                    <% end %>
                    </h2>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
    </div>
</div>

app/views/cooks/likes.html.erb
<div class="index">
    <div class="container">
        <div class="index-wrapper">
          <% @cooks.each do |cook|%>
            <div class="index-content">
              <%= link_to(cook) do %>
                <div class="index-content-image">
                    <%= image_tag cook.image.url, class:"index-img"%>
                </div>
                <div class="index-content-name">
                    <h2>
                    <%= cook.name %>
                    <% if cook.score >= 90 %>
                      <span class="fa fa-heart"></span>
                    <% end %>
                    </h2>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
    </div>
</div>

app/views/cooks/new.html.erb
<div class="new-cook">
    <div class="container">
        <div class="new-cook-wrapper">
            <%= form_with(model: @cook) do |f|%>
            <%= render("shared/error_message", model: f.object) %>
                <div class="new-cook-line">
                    <p><%= f.label :image, "-完成品-"%></p>
                    <p><%= f.file_field :image, class:"text-field" %></p>
                </div>
                <div class="new-cook-line">
                    <p><%= f.label :name, "-料理名-" %></p>
                    <p><%= f.text_field :name, class:"text-field",
                        placeholder: "例: 肉じゃが" %></p>
                </div>
                <div class="new-cook-line">
                    <p><%= f.label :material, "-材料-" %></p>
                    <p><%= f.text_area :material, class:"text-field area",
                        placeholder: "例:
・醤油 大さじ２☆
・砂糖 大さじ１☆
・調理酒 大さじ2☆
・みりん 大さじ2☆
・水 200ml☆
・牛肉 200g
・じゃがいも 2個
・にんじん 1個
・玉ねぎ 1個"
                    %></p>
                </div>
                <div class="new-cook-line">
                    <p><%= f.label :Process, "-工程-" %></p>
                    <p><%= f.text_area :Process, class:"text-field area",
                        placeholder: "例:
①野菜を一口大に切る
②肉を食べやすい大きさに切る
③油をひいて肉を焼く
④肉を取り出して野菜を焼く
⑤ある程度火が通ったら、☆の材料を入れて煮る
⑥野菜が柔らかくなってきたら、肉を入れて少し煮る"
                     %></p>
                </div>
                <div class="new-cook-line">
                    <p><%= f.label :memo, "-メモ-" %></p>
                    <p><%= f.text_area :memo, class:"text-field area",
                        placeholder: "例:
・しっかり煮ないとにんじんカチカチ（最低30分以上は煮る）
・完成後味が薄かったら、醤油と塩と砂糖で調節する"
                    %></p>
                </div>
                <div class="new-cook-line">
                    <p><%= f.label :score, "-点数-" %></p>
                    <p><%= f.number_field :score, class: "text-field", placeholder:"気持ちはいつも100点です！" %></p>
                </div>
                <div class="new-cook-line submit-line">
                <%= f.hidden_field :created_at, value: Date.today %>
                <p><%= f.submit "ご馳走様でした！", {class: "submit"} %></p>
                </div>
            <% end %>

        </div>
    </div>
</div>

app/views/cooks/show.html.erb
<div class="show">
    <div class="container">
        <div class="show-wrapper">
            <div class="show-left">
                <div class="show-date">
                    <p><%= "作成日：#{@cook.created_at.to_s(:datetime)}" %></p>
                </div>
                <div class="show-image">
                    <%= image_tag @cook.image.url, class: "show-img"%>
                    <div class="show-score">
                        <h2><%= "#{@cook.score}pt" %></h2>
                    </div>
                </div>
                <div class="show-name">
                    <h1><%= @cook.name %></h1>
                </div>
            </div>
            <div class="show-right">
                <div class="cooking">
                    <div class="show-line">
                        <div class="show-line-title">
                            <h3>材料</h3>
                        </div>
                        <div class="show-line-content">
                            <p><%= @cook.material %></p>
                        </div>
                    </div>
                    <div class="show-line border">
                        <div class="show-line-title">
                            <h3>作り方</h3>
                        </div>
                        <div class="show-line-content">
                            <p><%= @cook.Process %></p>
                        </div>
                    </div>
                </div>
                <div class="show-memo">
                    <div class="show-memo-title">
                        <h3>メモ</h3>
                    </div>
                    <div class="show-line-content">
                        <p><%= @cook.memo %></p>
                    </div>
                </div>
                <div class="edit">
                    <%= link_to("編集", edit_cook_path, class:"update") %>
                    <%= link_to("削除", cook_path(@cook.id), method: :delete, data: { confirm: "本当に削除しますか？" }, class:"update") %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CookingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container">
        <div class="header-title">
          <h1><%=link_to("みなこの料理日記",cooks_path) %></h1>
        </div>
        <div class="resp-header-title">
          <%= link_to(cooks_path, class:"title-link") do %>
          <h1>みなこの<br>料理日記</h1>
          <% end %>
        </div>
        <div id="header-nav-btn">
          <span class="fa fa-bars" id="show-btn"></span>
        </div>
      </div>
    </header>
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <div class="header-nav">
      <p><%= link_to("レシピ一覧", cooks_path, class:"link btn nav-btn")%><span class="fa fa-book"></span></p>
      <p><%= link_to("お気に入り一覧", cooks_likes_path, class:"link btn nav-btn")%><span class="fa fa-heart"></span></p>
      <p><%= link_to("レベルアップ", new_cook_path, class:"link btn nav-btn")%><span class="fa fa-level-up-alt"></span></p>
    </div>
    <%= yield %>
    <footer>
      <div class="container">
        <h3>目指せ！100食！</h3>
        <h3 class="total">現在：計<span><%= @count %></span>食</h3>
      </div>
    </footer>
  </body>
</html>

app/views/shared/_error_message.html.erb
<% if model.errors.any? %>
  <div class="alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>